import {readFileSync,writeFileSync,mkdirSync,cpSync,readdirSync,statSync,existsSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {parse} from 'dotenv';import {hash} from '../packages/core/src/index.ts';
if(execFileSync('git',['status','--porcelain']).toString().trim())throw new Error('PACKAGE_REQUIRES_CLEAN_COMMIT');
const commit=execFileSync('git',['rev-parse','HEAD']).toString().trim(),out='dist/afr-submission-'+commit.slice(0,8);mkdirSync(out,{recursive:true});execFileSync('git',['archive','--format=tar','-o',out+'/source.tar','HEAD']);cpSync('dist/afr-verify',out+'/afr-verify',{recursive:true});cpSync('docs',out+'/docs',{recursive:true});cpSync('deployments',out+'/deployments',{recursive:true});
const report=JSON.parse(readFileSync('runs/AI-STATUS.json','utf8'));cpSync(report.results_directory,out+'/evaluation',{recursive:true});
const cases=['0x06f91c2a95e0cd8bb3203f5f7d8b3a55','0x11624f7699b9dca9b8cf02b3484a7be6','0x48d71f578160c5fa7aefbe431ce92f71','0x7c7ef848f969c655a37ae2330459132f'];
for(const id of cases)if(existsSync('runs/'+id)){mkdirSync(out+'/cases/'+id,{recursive:true});for(const name of readdirSync('runs/'+id))if(/^(packet|public)-v\d+\.zip$|^(verify.*|LIVE-RESULT)\.json$/.test(name))cpSync('runs/'+id+'/'+name,out+'/cases/'+id+'/'+name);}
cpSync('runs/0x06f91c2a95e0cd8bb3203f5f7d8b3a55/negatives',out+'/negatives',{recursive:true});
mkdirSync(out+'/qa',{recursive:true});for(const p of ['runs/evaluation-audit.json','runs/recovery-check.json','runs/final-offline.json','runs/final-rpc-unavailable.json','coverage/coverage-summary.json','runs/security-check.json','runs/slither-vault-solc.json','runs/slither-EvidenceAnchor.json','runs/slither-AFRTestUSD.json','runs/ego/core-browser-vectors.json','runs/ego/qa-continuous.mp4','runs/ego/complete-run.mp4','runs/ego/complete-run/recording.json'])if(existsSync(p))cpSync(p,out+'/qa/'+p.split('/').at(-1));
const secrets=readdirSync('.secrets').filter(n=>n.endsWith('.env')).flatMap(n=>Object.entries(parse(readFileSync('.secrets/'+n))).filter(([k,v])=>/(PK|KEY|SECRET|TOKEN|PASSWORD)/.test(k)&&v.length>=16).map(([,v])=>v));const inventory:any[]=[];function walk(path:string){for(const name of readdirSync(path)){const full=path+'/'+name;if(statSync(full).isDirectory())walk(full);else{const bytes=readFileSync(full);if(secrets.some(s=>bytes.includes(Buffer.from(s))))throw new Error('SECRET_IN_ARTIFACT:'+full);inventory.push({path:full.slice(out.length+1),bytes:bytes.length,sha256:hash(bytes)});}}}walk(out);
writeFileSync(out+'/MANIFEST.json',JSON.stringify({source_commit:commit,created_at:new Date().toISOString(),status:'LOCAL RELEASE CANDIDATE; human wallet/video, 72h and publication gates may remain pending',ai:report,files:inventory},null,2));writeFileSync(out+'/START-HERE.txt','Read docs/implementation/HACKATHON-STATUS.md and docs/demo/RUNBOOK.md. Source: source.tar. Independent CLI: node afr-verify/afr-verify.mjs cases/<id>/packet-v1.zip --json. This package contains synthetic evidence and real testnet results; QA videos are automated, not human signoffs. No secrets are included.\n');execFileSync('tar',['-czf',out+'.tgz','-C','dist',out.split('/').at(-1)!]);console.log({artifact:out+'.tgz',files:inventory.length,secret_scan:'PASS'});
