import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,cpSync,readdirSync,statSync} from 'node:fs';
import {parse} from 'dotenv';
import {hash} from '../packages/core/src/index.ts';
if(execFileSync('git',['status','--porcelain']).toString().trim())throw Error('CLEAN_COMMIT_REQUIRED');
const head=execFileSync('git',['rev-parse','HEAD']).toString().trim(),out='dist/afr-beta-0.2.0-'+head.slice(0,8);mkdirSync(out,{recursive:true});
for(const pkg of ['afr-verify','afr-recorder']){const b=JSON.parse(readFileSync('dist/'+pkg+'/BUILD.json','utf8'));if(b.source_commit!==head||b.source_dirty!==false||b.release_candidate!==true)throw Error('CLEAN_RELEASE_BUILD_REQUIRED');}
execFileSync('git',['archive','--format=tar','-o',out+'/source.tar','HEAD']);cpSync('dist/afr-verify',out+'/afr-verify',{recursive:true});cpSync('dist/afr-recorder-0.2.0-beta.1.tgz',out+'/afr-recorder-0.2.0-beta.1.tgz');cpSync('docs/product',out+'/docs',{recursive:true});cpSync('docs/validation/beta',out+'/validation',{recursive:true});
cpSync('runs/beta-ui/downloads',out+'/evidence',{recursive:true});cpSync('runs/browser/downloaded.zip',out+'/evidence/final-packet.zip');
const latest=JSON.parse(readFileSync('runs/BETA-LATEST.json','utf8'));mkdirSync(out+'/external-agent',{recursive:true});for(const name of readdirSync(latest.output))if(/^(model-(request|response)-\d+|RESULT|receipt)\.json$/.test(name))cpSync(latest.output+'/'+name,out+'/external-agent/'+name);
writeFileSync(out+'/START-HERE.md','# AFR 0.2.0-beta.1\n\nRead docs/BETA-RESULTS.md for verified scope and remaining gates. To start a fresh recording workspace: extract source.tar, read its README, then pnpm install --frozen-lockfile; pnpm setup:local --recorder-only; pnpm build; pnpm build:cli; pnpm start:recorder. Requires Node 22 and pnpm 9.\n\nInstall the recorder tgz in your Agent project; docs/SDK-GUIDE.md explains mapping. Existing evidence can be verified immediately with node afr-verify/afr-verify.mjs evidence/<file>.zip --json. Snapshots intentionally return incomplete; final packets use a separate strict profile.\n\nIncluded CLI trust is for this issuing instance. A new instance generates its own trust configuration. No secrets or databases included. Testnet/synthetic data only; not a hosted insurance service.\n');
const secrets=readdirSync('.secrets').filter(n=>n.endsWith('.env')).flatMap(n=>Object.entries(parse(readFileSync('.secrets/'+n))).filter(([k,v])=>/(PK|KEY|SECRET|TOKEN|PASSWORD)/.test(k)&&v.length>=16).map(([,v])=>v));const files:any[]=[];
function walk(dir:string){for(const name of readdirSync(dir)){const path=dir+'/'+name;if(statSync(path).isDirectory())walk(path);else{const bytes=readFileSync(path);if(secrets.some(s=>bytes.includes(Buffer.from(s))))throw Error('SECRET_IN_PACKAGE:'+path);files.push({path:path.slice(out.length+1),bytes:bytes.length,sha256:hash(bytes)});}}}walk(out);
writeFileSync(out+'/MANIFEST.json',JSON.stringify({source_commit:head,version:'0.2.0-beta.1',at:new Date().toISOString(),published:false,files},null,2));execFileSync('tar',['-czf',out+'.tgz','-C','dist',out.split('/').at(-1)!]);console.log({artifact:out+'.tgz',files:files.length,secret_scan:'PASS'});
